CREATE DATABASE IF NOT EXISTS colegio_app
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE colegio_app;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(80) NOT NULL UNIQUE,
  contrasena VARCHAR(255) NOT NULL,
  rol ENUM('admin', 'docente') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
